version: '3.8'

services:
  mysql:
    image: mirel-mysql:latest
    build:
      context: /mnt/d/dev/mysql-docker
      dockerfile: .devcontainer/Dockerfile
    container_name: mirel_mysql_container
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - .:/workspace

volumes:
  mysql_data:
